# Generated by Django 4.2.23 on 2025-10-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_investment_systemnotification_systemconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('livestock', 'Livestock'), ('real_estate', 'Real Estate'), ('business', 'Business'), ('technology', 'Technology'), ('manufacturing', 'Manufacturing'), ('bonds', 'Bonds'), ('treasury_bills', 'Treasury Bills'), ('stocks', 'Stocks & Securities'), ('mutual_funds', 'Mutual Funds'), ('fixed_deposits', 'Fixed Deposits'), ('microfinance', 'Microfinance'), ('other', 'Other')], max_length=50),
        ),
    ]
