# Generated by Django 4.2.23 on 2025-10-22 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_investment_investment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='core_objective',
            field=models.TextField(blank=True, help_text='Core investment objective', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current price per unit/share', max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes (not visible to users)', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_thesis',
            field=models.TextField(blank=True, help_text='Detailed investment thesis and analysis', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='key_metrics',
            field=models.TextField(blank=True, help_text='Key financial metrics (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='risks',
            field=models.TextField(blank=True, help_text='Key risks (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='source_url',
            field=models.URLField(blank=True, help_text='Source URL for more information', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='strengths',
            field=models.TextField(blank=True, help_text='Key strengths (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='ticker_symbol',
            field=models.CharField(blank=True, help_text='Ticker symbol if publicly traded', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='time_horizon',
            field=models.CharField(blank=True, help_text='Expected investment time horizon', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='description',
            field=models.TextField(help_text='Brief description of the investment'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('livestock', 'Livestock'), ('real_estate', 'Real Estate'), ('business', 'Business'), ('technology', 'Technology'), ('manufacturing', 'Manufacturing'), ('bonds', 'Bonds'), ('treasury_bills', 'Treasury Bills'), ('stocks', 'Stocks & Securities'), ('mutual_funds', 'Mutual Funds'), ('fixed_deposits', 'Fixed Deposits'), ('microfinance', 'Microfinance'), ('other', 'Other')], help_text='Type of investment', max_length=50),
        ),
        migrations.AlterField(
            model_name='investment',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', help_text='Risk level of the investment', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('completed', 'Completed')], default='draft', help_text='Current status of the investment', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='title',
            field=models.CharField(help_text='Name of the investment opportunity', max_length=255),
        ),
        migrations.CreateModel(
            name='InvestmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='investment_documents/%Y/%m/%d/')),
                ('document_type', models.CharField(choices=[('prospectus', 'Prospectus'), ('financials', 'Financial Statements'), ('legal', 'Legal Documents'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_documents', to='dashboard.investment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
