# Generated by Django 5.2 on 2025-05-27 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_date', models.DateField()),
                ('cycle_end_date', models.DateField()),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distributed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_finalized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_distributions', to=settings.AUTH_USER_MODEL)),
                ('kikoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='groups.kikoba')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contribution_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to=settings.AUTH_USER_MODEL)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_profits', to='reports.profitdistribution')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('member_statement', 'Member Statement'), ('group_financial', 'Group Financial Report'), ('profit_distribution', 'Profit Distribution Report')], max_length=20)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('custom', 'Custom Period')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=5)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('kikoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='groups.kikoba')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
