# Generated by Django 5.2 on 2025-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="kikoba_number",
        ),
        migrations.AddField(
            model_name="user",
            name="nida_number",
            field=models.CharField(
                blank=True,
                help_text="National ID number, if available.",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_identifier",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for the user, can be NIDA or system-generated.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_method",
            field=models.CharField(
                blank=True,
                help_text="e.g., NIDA, PHONE_PHOTO_MEMBER_VERIFIED",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_status",
            field=models.CharField(
                default="pending",
                help_text="e.g., pending, verified, rejected",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("member", "Member"),
                    ("kikoba_admin", "Kikoba Admin"),
                ],
                default="member",
                max_length=15,
            ),
        ),
    ]
