# Generated by Django 5.2 on 2025-05-29 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_remove_user_kikoba_number_user_nida_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_identifier",
        ),
    ]
