# Generated by Django 4.2.23 on 2025-10-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_user_user_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('kikoba_admin', 'Kikoba Admin'), ('accountant', 'Accountant')], default='member', max_length=15),
        ),
    ]
