# Generated by Django 5.2 on 2025-05-29 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_kikoba_constitution_document_and_more"),
        ("loans", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={
                "ordering": ["-disbursement_date"],
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
            },
        ),
        migrations.RemoveField(
            model_name="loan",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="application_date",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="approval_date",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="borrower",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="interest_accrued",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="interest_rate",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="penalties_accrued",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="term_days",
        ),
        migrations.AddField(
            model_name="loan",
            name="closed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="current_due_date",
            field=models.DateField(
                blank=True,
                help_text="Current due date, may change if rescheduled",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="disbursed_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="loan",
            name="disbursement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="interest_rate_at_disbursement",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Interest rate applied at the time of disbursement",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="original_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="repayment_schedule_details",
            field=models.JSONField(
                blank=True,
                help_text="Details of the repayment schedule, e.g., installments, due dates",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="total_repayable",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Principal + Interest",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_disbursement", "Pending Disbursement"),
                    ("active", "Active"),
                    ("paid_on_time", "Paid on Time"),
                    ("late", "Late"),
                    ("defaulted", "Defaulted"),
                    ("cleared_early", "Cleared Early"),
                    ("rescheduled", "Rescheduled"),
                ],
                default="pending_disbursement",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("purpose", models.TextField()),
                (
                    "application_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Reason for approval/rejection", null=True
                    ),
                ),
                (
                    "decision_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_loan_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kikoba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kikoba_loan_applications",
                        to="groups.kikoba",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Application",
                "verbose_name_plural": "Loan Applications",
                "ordering": ["-application_date"],
            },
        ),
        migrations.AddField(
            model_name="loan",
            name="application",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_details",
                to="loans.loanapplication",
            ),
        ),
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Emergency Loan, Development Loan",
                        max_length=255,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate in percentage, e.g., 10 for 10%",
                        max_digits=5,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "min_duration_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Minimum loan duration in days"
                    ),
                ),
                (
                    "max_duration_days",
                    models.PositiveIntegerField(
                        help_text="Maximum loan duration in days"
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Grace period in days before first repayment is due",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "kikoba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_products",
                        to="groups.kikoba",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Product",
                "verbose_name_plural": "Loan Products",
            },
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="loan_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loans.loanproduct",
            ),
        ),
        migrations.CreateModel(
            name="Repayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mobile_money", "Mobile Money"),
                            ("bank_transfer", "Bank Transfer"),
                            (
                                "internal_transfer",
                                "Internal Transfer/Savings Deduction",
                            ),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=30,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified by Kikoba Admin"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="loans.loan",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_repayments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Repayment",
                "verbose_name_plural": "Repayments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.DeleteModel(
            name="LoanRepayment",
        ),
    ]
