# Generated by Django 4.2.23 on 2025-10-23 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0003_alter_loan_options_remove_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_id_number',
            field=models.CharField(blank=True, help_text='National ID or voter ID number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='loan_applications/ids/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='loan_applications/applicants/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='applicant_signature',
            field=models.ImageField(blank=True, null=True, upload_to='loan_applications/signatures/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='collateral_description',
            field=models.TextField(blank=True, help_text='Description of collateral provided', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Interest rate in percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly payment amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='purpose_description',
            field=models.TextField(blank=True, help_text='Detailed purpose description', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_period',
            field=models.IntegerField(default=12, help_text='Repayment period in months'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount including interest', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='purpose',
            field=models.CharField(choices=[('business', 'Business'), ('education', 'Education'), ('medical', 'Medical'), ('agriculture', 'Agriculture'), ('housing', 'Housing'), ('emergency', 'Emergency'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of guarantor', max_length=255)),
                ('phone_number', models.CharField(help_text='Phone number (format: 255XXXXXXXXX)', max_length=12)),
                ('id_number', models.CharField(help_text='National ID or voter ID number', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='loan_applications/guarantors/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='loan_applications/guarantor_signatures/')),
                ('guaranteed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount guaranteed (optional)', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loanapplication')),
                ('member', models.ForeignKey(blank=True, help_text='If guarantor is a kikoba member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Guarantor',
                'verbose_name_plural': 'Loan Guarantors',
                'ordering': ['created_at'],
            },
        ),
    ]
