# Generated by Django 5.2 on 2025-05-27 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kikoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contribution_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('loan_limit_factor', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('loan_term_days', models.PositiveIntegerField(default=90)),
                ('late_payment_penalty', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_center_kikoba', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KikobaInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_or_phone', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('member', 'Member'), ('chairperson', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('kikoba_admin', 'Kikoba Admin')], default='member', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KikobaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('chairperson', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('kikoba_admin', 'Kikoba Admin')], default='member', max_length=15)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
