# Generated by Django 5.2 on 2025-05-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kikoba',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_vikoba', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kikobainvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_kikoba_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kikobainvitation',
            name='kikoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kikoba_invitations', to='groups.kikoba'),
        ),
        migrations.AddField(
            model_name='kikobamembership',
            name='kikoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kikoba_memberships', to='groups.kikoba'),
        ),
        migrations.AddField(
            model_name='kikobamembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_kikoba_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kikobamembership',
            unique_together={('kikoba', 'user')},
        ),
    ]
