# Generated by Django 5.2 on 2025-05-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kikoba',
            name='constitution_document',
            field=models.FileField(blank=True, help_text="Upload the Kikoba's constitution document (optional).", null=True, upload_to='kikoba_documents/constitutions/'),
        ),
        migrations.AddField(
            model_name='kikoba',
            name='estimated_members',
            field=models.CharField(blank=True, choices=[('2-5', '2-5 Members'), ('6-10', '6-10 Members'), ('11-20', '11-20 Members'), ('21-50', '21-50 Members'), ('51-100', '51-100 Members'), ('101-200', '101-200 Members'), ('201-500', '201-500 Members'), ('501-1000', '501-1000 Members'), ('1000+', '1000+ Members')], help_text='Estimated number of members in the Kikoba.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kikoba',
            name='kikoba_number',
            field=models.CharField(blank=True, help_text='Unique identification number for the Kikoba.', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='kikoba',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location or address of the Kikoba.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kikoba',
            name='other_documents',
            field=models.FileField(blank=True, help_text='Upload any other relevant documents for the Kikoba (optional).', null=True, upload_to='kikoba_documents/others/'),
        ),
        migrations.AlterField(
            model_name='kikoba',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kikoba',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vikoba', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kikoba',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kikoba',
            name='is_center_kikoba',
            field=models.BooleanField(default=False, help_text='Can new members join this Kikoba directly from a central registration form?'),
        ),
        migrations.AlterField(
            model_name='kikoba',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
