# Generated by Django 5.2 on 2025-05-29 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0003_kikoba_constitution_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyFundContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contributed_on", models.DateField(auto_now_add=True)),
                (
                    "kikoba_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_fund_contributions",
                        to="groups.kikobamembership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntryFeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_fully_paid", models.BooleanField(default=False)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "kikoba_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.kikobamembership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntryFeeInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_on", models.DateField(auto_now_add=True)),
                (
                    "entry_fee_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="groups.entryfeepayment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KikobaContributionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "entry_fee_due_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Days to pay entry fee from joining"
                    ),
                ),
                (
                    "share_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "share_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "share_due_day",
                    models.PositiveIntegerField(
                        blank=True, help_text="Day of period shares are due", null=True
                    ),
                ),
                (
                    "emergency_fund_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("emergency_fund_required", models.BooleanField(default=False)),
                (
                    "min_saving_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_saving_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "kikoba",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_config",
                        to="groups.kikoba",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Saving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("saved_on", models.DateField(auto_now_add=True)),
                (
                    "kikoba_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings",
                        to="groups.kikobamembership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_fully_paid", models.BooleanField(default=False)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "kikoba_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.kikobamembership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShareInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_on", models.DateField(auto_now_add=True)),
                (
                    "share_contribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="groups.sharecontribution",
                    ),
                ),
            ],
        ),
    ]
