# Generated by Django 4.2.23 on 2025-10-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_emergencyfundcontribution_entryfeepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kikoba',
            name='creator_phone_number',
            field=models.CharField(blank=True, help_text='Phone number of the user who initiated creation.', max_length=15, null=True),
        ),
    ]
