# Generated by Django 4.2.23 on 2025-10-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_kikoba_creator_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kikobainvitation',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('chairperson', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('kikoba_admin', 'Kikoba Admin'), ('accountant', 'Accountant')], default='member', max_length=15),
        ),
        migrations.AlterField(
            model_name='kikobamembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('chairperson', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('kikoba_admin', 'Kikoba Admin'), ('accountant', 'Accountant')], default='member', max_length=15),
        ),
    ]
