# Generated by Django 4.2.23 on 2025-10-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_kikobainvitation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryfeepayment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entryfeepayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entryfeepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
