# Generated by Django 4.2.23 on 2025-11-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_entryfeepayment_notes_entryfeepayment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kikoba',
            name='group_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard VIKOBA (Variable-Share ASCA)'), ('fixed_share', 'Fixed-Share VIKOBA'), ('interest_refund', 'Interest Refund VIKOBA'), ('rosca', 'ROSCA (Rotating Savings)'), ('welfare', 'Welfare/Help Group (WCG)')], help_text='Type of the group which determines the financial model used.', max_length=20, null=True),
        ),
    ]
