# Generated by Django 4.2.23 on 2025-11-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_add_group_type_to_kikoba'),
        ('groups', '0009_add_group_type_to_kikoba'),
    ]

    operations = [
    ]
