# Generated by Django 4.2.23 on 2025-11-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_merge_20251116_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='kikobainvitation',
            name='invitation_code',
            field=models.CharField(blank=True, help_text='Unique invitation code (e.g., WA-123456)', max_length=20, unique=True),
        ),
    ]
